image: ubuntu

services:
  - docker:dind

before_script:
  - docker info

build:
  before_script:
      - apt-get update
      - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
      - apt-get install -y wget
      - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
      - apt-get update
      - apt-get install -y heroku-toolbelt
      - gem install dpl
  variables:
      HEROKU_API_KEY: $HEROKU_ACCOUNT_KEY
  script:
      - dpl --provider=heroku --app=staging-formulariocontato --api-key=$HEROKU_API_KEY
      - heroku run rake db:migrate --exit-code --app staging-formulariocontato
  stage: build
 